// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5aSToZvf3FTXPFI9tSoCU8YDudaHmCYY',
    appId: '1:862383259193:web:ec64e7b02ec2a05f0117e8',
    messagingSenderId: '862383259193',
    projectId: 'platepost-8ce3d',
    authDomain: 'platepost-8ce3d.firebaseapp.com',
    storageBucket: 'platepost-8ce3d.firebasestorage.app',
    measurementId: 'G-RDK511GE5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGjPsKdM2upoV7gp5c2U9PJ_3oJUeeQT0',
    appId: '1:862383259193:android:03266bbe29c206fb0117e8',
    messagingSenderId: '862383259193',
    projectId: 'platepost-8ce3d',
    storageBucket: 'platepost-8ce3d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5aSToZvf3FTXPFI9tSoCU8YDudaHmCYY',
    appId: '1:862383259193:web:4dd75be54ced91b00117e8',
    messagingSenderId: '862383259193',
    projectId: 'platepost-8ce3d',
    authDomain: 'platepost-8ce3d.firebaseapp.com',
    storageBucket: 'platepost-8ce3d.firebasestorage.app',
    measurementId: 'G-X7LN3ZMKRW',
  );
}
